### PR TITLE
Move to mono repo

### PR DESCRIPTION
**Pull request by GRVYDEV**
This PR will move to a monorepo structure. This will:
- Make docs easier
- Make docker easier
- Simplify the project structure

### CODE REVIEW

**Comment by SpoopyTim** [comment]
Change `lightspeed-ingest` to `ingest` because its all contained in the main repo now, same with the other folder

**Comment by GRVYDEV** [comment]
> Change `lightspeed-ingest` to `ingest` because its all contained in the main repo now, same with the other folder

good shout

**Review by SpoopyTim — CHANGES_REQUESTED** [review]
Pull out the images folder from both added directories and move it to the root one, update any links / documentation accordingly

**Review by SpoopyTim — CHANGES_REQUESTED** [review]
Move licences to root directory and combine all readme's into one. Alternatively move all readme's to the root directory under different names for easier refactoring later.

**Review by SpoopyTim — CHANGES_REQUESTED** [review]
Duplicate images `react/images/lightspeedlogo.svg` and `react/public/images/lightspeedlogo.png`

**Comment by SpoopyTim** [comment]
Unifying the gitignore is an interesting change, it would be easier to manage if it were split across directories and would make more sense since the root directory dosent have any project files in it

**Review by SpoopyTim — CHANGES_REQUESTED** [review]
Rename `react` to `frontend`, yes it runs on react but we dont call the ingest server `rust`

**Review by SpoopyTim — APPROVED** [review]
We got there in the end! LGTM!

**Review by SpoopyTim — CHANGES_REQUESTED** [review]
One small detail is in the comments in the compose file, make sure theres no double `#`

**Pull request merged**
