### PR TITLE
Cloud-Init/bash script installer for Ubuntu 20.04

### PR DESCRIPTION
**Pull request by EnigmaCurry**
Hi, this project is so awesome, fantastic :1st_place_medal: 

This is an installer script to install all the components from source code, and that works tested on a $5 DigitalOcean droplet (Ubuntu 20.04). You just have to paste the entire script into the droplet creation screen, under the section called `User data` (its a checkbox that opens a text-area. Paste the entire script into the text-area) The `User data` is cloud-init, it will run the install script when the droplet starts. See the top of the script for more details.

The git repositories to clone are configurable, as well as the branch or commit to checkout. This makes it easy to test from a fork or PR branch. ~~Right now I have it set to use the PR from https://github.com/GRVYDEV/Lightspeed-ingest/pull/24 so that is generates a random stream key by default.~~ Now that PR has been merged we're back on master.

~~This also installs Caddy, which serves the react static HTML.~~ Now this install nginx and certbot. certbot creates TLS (HTTPs) certificates and nginx proxys the websocket (wss:// to ws://).

### CODE REVIEW

**Comment by GRVYDEV** [comment]
This is awesome! So a couple of things. 1) I want to get the stream key merged in before this does so you can have it pull from master! 2) we have switched to using nginx for the react site. Would this change your implementation at all?

**Comment by EnigmaCurry** [comment]
ok cool, let me check out the new nginx config, yea I can use that instead of Caddy, no problem! Thanks

**Comment by GRVYDEV** [comment]
> ok cool, let me check out the new nginx config, yea I can use that instead of Caddy, no problem! Thanks

Awesome :)

**Comment by GRVYDEV** [comment]
We had 2 PRs Merged into master of ingest. 1 dealing with the streamkey 1 dealing with the IP which it will listen on. Take a look!

**Comment by EnigmaCurry** [comment]
I've ripped out Caddy and replaced with nginx, (and we no longer need the streamkey branch anymore, we're back on master yay!)

I'm testing with TLS and it's still not working. All the logs look normal, not seeing error anywhere just isn't working. The websocket is proxied through SSL fine, I see it connect, and see evidence in the javascript console and the webrtc log, but it never starts the video stream.

**Comment by EnigmaCurry** [comment]
This is where I'm proxying the websocket with nginx:

https://github.com/GRVYDEV/Project-Lightspeed/pull/26/files#diff-6699e60df884980ffdfb0d23e39d305e673c8a4a55509aefcfaa0744f46263d6R223-R229

(FYI where you see the `@@@` characters, it is being replaced as `$` in the bash HEREDOC piped to sed.)

**Comment by EnigmaCurry** [comment]
I do now understand why its not working. I was binding webrtc to localhost, thinking I could proxy it but webrtc uses those other ports. .. I will test and fix shortly.

**Comment by EnigmaCurry** [comment]
OK cool, now its work with TLS. If I understand correctly what I've done, Its just the HTML and the websocket that is TLS on port 443, the video is webrtc done via higher ports and is not encrypted. Anyway, this is sufficient in order to be able to embed in an iframe of another TLS website. 

I'm testing this in app.kosmi.io, it embeds the TLS enabled lightspeed inside the Kosmi.io chat client. SOO cool :sunglasses:

**Comment by GRVYDEV** [comment]
Is this completed?

**Comment by EnigmaCurry** [comment]
It's tested working and complete for DigitalOcean.

I was testing this script on an 20.04 Virtual Machine locally in KVM, which had a weird problem compiling the react code:

```
root@lightspeed:~/git/Lightspeed-react# node --version
v14.15.4
root@lightspeed:~/git/Lightspeed-react# npm --version
6.14.10
root@lightspeed:~/git/Lightspeed-react# npm install

> ejs@2.7.4 postinstall /root/git/Lightspeed-react/node_modules/ejs
> node ./postinstall.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/root/git/Lightspeed-react/node_modules/ejs/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.2.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ejs@2.7.4 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ejs@2.7.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-07T20_55_04_492Z-debug.log
```

I can't even add ejs@2.7.4 to a fresh npm project, it fails the same way. What did end up working was using yarn. I can't figure out what is wrong with npm on this VM. I don;t have this problem on DigitalOcean droplet.

**Comment by HerrTaschenbier98** [comment]
I have the same problem on my VMWare VM. 
To solve the npm warnings, you could try to use the installation command: 'npm install -g npm-install-peers'. This work for me.
> I was testing this script on an 20.04 Virtual Machine locally in KVM, which had a weird problem compiling the react 
> npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.2.1 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})


But now I have the Error: 

```
npm run build

> lightspeed-react@0.1.0 build /root/git/Lightspeed-react
> react-scripts build

sh: 1: react-scripts: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! lightspeed-react@0.1.0 build: `react-scripts build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the lightspeed-react@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-08T10_49_36_005Z-debug.log
```

update:
Also on my Ubuntu 20.04 Laptop the Error appears.

**Comment by EnigmaCurry** [comment]
@HerrTaschenbier98 thanks, I was able to get around this by upgrading to the latest upstream version (non-LTS) of node and npm:

```
    curl -sL https://deb.nodesource.com/setup_15.x | bash -
    apt-get install -y nodejs
```

I've added this to the script, and it compiles fine now. @GRVYDEV I think this is ready for review now!

**Comment by EnigmaCurry** [comment]
I found some extra nginx config (thanks Phatti McButterpants) I need to add, let me test that, hang on.

**Comment by EnigmaCurry** [comment]
OK, done, works.

**Comment by GRVYDEV** [comment]
Merged :)

**Comment by GRVYDEV** [comment]
Would you be willing to write a readme for this functionality?

**Comment by EnigmaCurry** [comment]
OK, you bet.

**Comment by GRVYDEV** [comment]
> OK, you bet.

You could do it in the contrib folder and then I will link to it from the main readme!

**Pull request merged**
